backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: boloko
    api_key: 615759249279911

collections:

  - name: 'vinhos'
    label: 'vinhos'
    folder: 'content/vinhos'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Nome do vinho', name: 'title', widget: 'string' }
      - { label: 'Nome da uva', name: 'type', widget: 'string' }
      - { label: 'Nome do local consumido', name: 'local', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'category', name: 'category', widget: 'string', default: 'vinhos' }
      - { label: 'cover', name: 'cover', widget: 'image' }
      - { label: 'rating', name: 'rating', widget: 'number', default: 2, min: 1, max: 3, value_type: "int"}
      - { label: 'price', name: 'price', widget: 'number', default: 2, min: 0, value_type: "int"}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'parmegianas'
    label: 'parmegianas'
    folder: 'content/parmegianologo'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Nome do restaurnate', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Nome do prato', name: 'description', widget: 'string' }
      - { label: 'category', name: 'category', widget: 'string', default: 'parmegianologo' }
      - { label: 'images', name: 'images', widget: 'image', choose_url: false,
          media_library: { config: { multiple: true }}}
      - { label: "acompanhamentos", name: "acompanhamentos", widget: "list", default: ["arroz"] }
      - { label: 'rating pessoal', name: 'rating', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_tecnica', name: 'rating_tecnica', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_carne', name: 'rating_carne', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_molho', name: 'rating_molho', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_crosta', name: 'rating_crosta', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_acompanhamentos', name: 'rating_acompanhamentos', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_restaurante', name: 'rating_restaurante', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'rating_maisvalia', name: 'rating_maisvalia', widget: 'number', default: 2, min: 1, max: 5, value_type: "int"}
      - { label: 'price', name: 'price', widget: 'number', default: 2, min: 0, value_type: "int"}
      - { label: 'porcao', name: 'porcao', widget: 'number', default: 1, min: 1, value_type: "int"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
